name: HotBlock
main: surva\hotblock\HotBlock
version: 1.1.3
api: 
- 3.0.0
- 4.0.0

depend: ["EconomyAPI"]

author: [survanetwork, naoki1510]
description: A funny PvP minigame
website: https://github.com/survanetwork/HotBlock

commands:
  pvp:
    description: command about pvp
    usage: /pvp [join|leave|chat]
    permission: true